### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by k-sheth** [jeffbski/joi-full#2]
Hi,

Sorry to be a pain, but the project is missing a LICENSE file and the default copyright license applies. I cannot use or distribute the lib :(

Could you kindly add the LICENSE file pls ?

Thanks

**Comment by jeffbski** [comment]
Sorry I had missed this originally. I have added that and uploaded to npm as v10.0.6-rel3

If I have missed anything else just let me know.
